services:
  ebisusbay-web:
    container_name: ebisusbay-web
    # platform: linux/arm64
    restart: no
    read_only: true
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile_local
      args:
        - NEXT_PUBLIC_ENV=testnet
        - NEXT_PUBLIC_SITE24X7_KEY=73ac6244ca4b768bc456621704482f32
        - NEXT_PUBLIC_SENTRY_DSN=https://340f040489c3da89454eb43040d73925@o1128536.ingest.sentry.io/4506126203420672
        - NEXT_PUBLIC_SENTRY_ENVIRONMENT=local-docker-compose
        - SENTRY_AUTH_TOKEN=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
        - NEXT_PUBLIC_WEB3MODAL_API_KEY=8002f872986e034df168060193915223
        - NEXT_FORCE_EDGE_IMAGES=true
        - TURBO_API=https://turborepo-remote-cache.ebisusbay.com # The address of a running turborepo-remote-cache server
        - TURBO_TEAM=eb-frontend-local # application/team
        - TURBO_TOKEN=VerySecret123 # Your secret key. This must be the same as the TURBO_TOKEN variable set on your turborepo-remote-cache server instance
        - TURBO_REMOTE_ONLY=false
        - TURBO_REMOTE_CACHE_TIMEOUT=120
        - TURBO_RUN_SUMMARY=true
    environment:
      PORT: '3000'
      EB_API_KEY: s48kQNFcCmC79NKm9CzQ
      CRONOSCAN_API_KEY: 6XET2BCQ2WHVQ3U8YQD297K3QSWDMA96BY
      APMINSIGHT_ENABLED: 'false'
      APMINSIGHT_LICENSE_KEY: us_25e4846c624d0af156763484be1e7e31
      APMINSIGHT_APP_NAME: local-ebisusbay-web-arm64-us-east-1
      APMINSIGHT_APP_PORT: '3000'
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:3000/api/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    tmpfs:
      - /home/node/.npm/_logs:mode=770,uid=1000,gid=1000
      - /home/node/.npm/_cacache:mode=770,uid=1000,gid=1000
      - /tmp:mode=770,uid=1000,gid=1000
    volumes:
      - ./volumes/ebisusbay-web_logs:/var/log/nodejs:rw
      # - ./volumes/ebisusbay-web_cache:/usr/src/app/apps/web/.next/cache:rw
      # - ./volumes/ebisusbay-web_apminsight:/usr/src/app/apminsightdata:rw
    ports:
      - 3000:3000

  ebisusbay-web-nginx:
    container_name: ebisusbay-web-nginx
    # platform: linux/arm64
    restart: no
    read_only: true
    build:
      context: .
      dockerfile: ./apps/web/proxy/Dockerfile_local
    environment:
      ## NGINX Amplify Agent
      AMPLIFY_API_KEY: b7f1ca270e79d8dc6350cd837b2b006b
      AMPLIFY_ENABLED: false
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:8080/api/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/lib/nginx
      - /etc/amplify-agent/custom
      - /tmp
    volumes:
      - ./volumes/ebisusbay-web-nginx_logs:/var/log/nginx:rw
      - ./volumes/ebisusbay-web-nginx_amplify_logs:/var/log/amplify-agent:rw"
    ports:
      - 8080:8080
    depends_on:
      - ebisusbay-web
    links:
      - ebisusbay-web
