services:
  ebisusbay-web:
    container_name: ebisusbay-web
    # platform: linux/arm64
    restart: no
    read_only: true
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile_local
      args:
        - NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV}
        - NEXT_PUBLIC_SITE24X7_KEY=${NEXT_PUBLIC_SITE24X7_KEY}
        - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
        - NEXT_PUBLIC_SENTRY_ENVIRONMENT=${NEXT_PUBLIC_SENTRY_ENVIRONMENT}
        - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
        - NEXT_PUBLIC_WEB3MODAL_API_KEY=${NEXT_PUBLIC_WEB3MODAL_API_KEY}
        - NEXT_FORCE_EDGE_IMAGES=${NEXT_FORCE_EDGE_IMAGES}
        - NEXT_PUBLIC_TRANSAK_ENV=${NEXT_PUBLIC_TRANSAK_ENV}
        - TURBO_API=${TURBO_API}
        - TURBO_TEAM=${TURBO_TEAM}
        - TURBO_TOKEN=${TURBO_TOKEN}
        - TURBO_REMOTE_ONLY=${TURBO_REMOTE_ONLY}
        - TURBO_REMOTE_CACHE_TIMEOUT=${TURBO_REMOTE_CACHE_TIMEOUT}
        - TURBO_RUN_SUMMARY=${TURBO_RUN_SUMMARY}
        - BITBUCKET_CICD_USERNAME=${BITBUCKET_CICD_USERNAME}
        - BITBUCKET_CICD_APP_PASSWORD=${BITBUCKET_CICD_APP_PASSWORD}
    environment:
      PORT: '3000'
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:3000/api/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    tmpfs:
      - /home/node/.npm/_logs:mode=770,uid=1000,gid=1000
      - /home/node/.npm/_cacache:mode=770,uid=1000,gid=1000
      - /tmp:mode=770,uid=1000,gid=1000
    volumes:
      - ./volumes/ebisusbay-web_logs:/var/log/nodejs:rw
    ports:
      - 3000:3000

  ebisusbay-web-nginx:
    container_name: ebisusbay-web-nginx
    # platform: linux/arm64
    restart: no
    read_only: true
    build:
      context: .
      dockerfile: ./apps/web/proxy/Dockerfile_local
    environment:
      # NGINX Amplify Agent
      AMPLIFY_API_KEY: b7f1ca270e79d8dc6350cd837b2b006b
      AMPLIFY_ENABLED: 'false'
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:8080/api/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/lib/nginx
      - /etc/amplify-agent/custom
      - /tmp
    volumes:
      - ./volumes/ebisusbay-web-nginx_logs:/var/log/nginx:rw
      - ./volumes/ebisusbay-web-nginx_amplify_logs:/var/log/amplify-agent:rw"
    ports:
      - 8080:8080
    depends_on:
      - ebisusbay-web
    links:
      - ebisusbay-web
