export default {
  Features: {
    AUCTION_OPTION_SALE: ' AUCTION_OPTION_SALE',
    CMS_NOTIFICATIONS: 'CMS_NOTIFICATIONS',
    CMS_FULL_PROFILES: 'CMS_FULL_PROFILES',
    GET_COLLECTION_NEW_ENDPOINT: 'GET_COLLECTION_NEW_ENDPOINT',
    CMS_COLLECTIONS: 'CMS_COLLECTIONS',
    VERIFIED_SWITCH_COLLECTION: 'VERIFIED_SWITCH_COLLECTION',
    VERIFIED_SWITCH_MARKETPLACE: 'VERIFIED_SWITCH_MARKETPLACE',
    INFINITE_QUERY_COLLECTION: 'INFINITE_QUERY_COLLECTION',
    UNVERIFIED_WARNING: 'UNVERIFIED_WARNING',
    REPORT_COLLECTION: 'REPORT_COLLECTION',
    NEW_CHAKRA_THEME: 'NEW_CHAKRA_THEME',
    GLOBAL_SEARCH: 'GLOBAL_SEARCH',
    BUNDLES: 'BUNDLES',
    GASLESS_LISTING: 'GASLESS_LISTING'
  },
  Variables: {
    PARAM: '{PARAM}',
  },
  Regex: {
    DEFAULT_WALLET_ID: /0x[a-fA-F0-9]{40}$/,
    BASE64_IMAGE:
      /^data:image\/(?:gif|png|jpeg|bmp|webp|svg\+xml)(?:;charset=utf-8)?;base64,(?:[A-Za-z0-9]|[+/])+={0,2}/,
    BASE64_VIDEO_MP4: /^data:video\/(?:mp4|webp|svg\+xml)(?:;charset=utf-8)?;base64,(?:[A-Za-z0-9]|[+/])+={0,2}/,
  },
}