
export const patchNotes = [
  {
    changeDate: '7.17.2023',
    patchNumber: ' Patch 0.3.0',
    notes: [`What another amazing week! Congrats to all of the winners! It has been great to see that 3D Slothy continues to earn rewards. @aces777wild 💧 has now taken ownership of this contract and will continue to lead the faction.` ,
    `Congrats to LHRC community for coming out last minute and taking home some points!`,
      
    `This week the multiplier for Mitama is 30! That is 1 troop for every 30 :mitama:` ,
      
    `Here is an update on how you will soon be able to put your land deeds to work for you after the reveal.`,
      
    `Owning the land will give you a portion of the proceeds generated by user gameplay in your land.` ,
      
    `For example, if you own a settlement and someone visits your tavern to mint a hero, you'll be paid a portion of that mint cost. If a group of heroes pay for entry into your dungeon in hopes to mint some rare loot, you'll receive a portion of the entry fee.`,
      
    `There will be several types of land and some land will require much more upkeep than others. All can be upgraded, cultivated, etc given enough work.`,
      
    `Land ownership will give a new layer of gameplay which will help you develop your heroes and tip the scales in dynasties warfare.  Somebody will reveal Ebisu's Bay the very settlement new players will start the game and where you access the game today.`,
      
    `Soon we'll release a more detailed roadmap and outline. We have a lot of exciting things planned!`]
  },
  {
    changeDate: '7.9.2023',
    patchNumber: ' Patch 0.2.0',
    notes: [`Our 2nd game of Ryoshi Dynasties has come to an end. Congrats to all of the winners and thank you so much to all who participated.`,
 
    `For the game this week the Mitama multiplier is 50 meaning  you will receive 1 troop fro every 50 :mitama:  you have.`,
    
    `This week's game will be one day longer ending on Monday instead of Sunday. Games will end on Mondays now.`
    ,
    `Unstaking from barracks will not be allowed if you have deployed or delegated troops, staking guards re-enabled.`,
    
    `Ryoshi Collections are received an honorary rewards bonus for listings this week.`,
    `10 points to VIPs`,
      `5 points for Tellers/Guards`,
      `2 points for Halloween/Xmas`,
    
      `New milestone for Fortune :fortune_token: staking, 3M tokens locked in the bank. 1/4 the circulating supply and $86k TVL.`,
    
      `Fortune reached #3 on the 24 hour volume charts for all cronos dex today.`]
  },
  {
    changeDate: '7.4.2023',
    patchNumber: ' Patch 0.1.0',
    notes:[ `Happy 4th of July to my fellow American frens.  Just a quick clarification on the rebalancing updates above ⁠📣│announcements`,

    `First note above finalized updated control point values. Next the clarification. `,
    `If a faction has a first place location in any control point they will not receive 2nd or 3rd place points, it will trickle down to 4th and 5th place.`,
    
    `Example: Factions A, B, C, D are playing.`,
    
    `Rankings for 2 points`,
    `point 1: 5 points`,
    `A`,
    ` B`,
    `C`,
    `D`,
    
    ` point 2: 3 points`,
    `C`,
    `A`,
    `B`,
    `D`,
    
    `Faction A will receive 5 points for point 1`,
    `Faction B  will receive 2 points for 1 and 2 points for 2`,
    `Faction C will receive 3 points for 2`,
    `Faction D will receive 1 point for 1 and 1 point for 2`,
    
    `The goal here to to distribute points more fairly to those smaller guilds and factions and encourage more participation. As always we'll continue to monitor gameplay and balance rewards and take feedback into consideration.`,
    `Cheers!`]
  }
]