export const host = 'https://cdn-prod.ebisusbay.com/files/ryoshi/avatars';

export const traits = [
  {
    name: 'Background',
    items: [
      { name: 'Jade', link: 'Background/Jade.png' },
      { name: 'Blue', link: 'Background/Blue.png' },
      { name: 'Orange', link: 'Background/Orange.png' },
      { name: 'Violet', link: 'Background/Violet.png' },
      { name: 'Green', link: 'Background/Green.png' },
      { name: 'Mercury', link: 'Background/Mercury.png' },
      { name: 'Sunset', link: 'Background/Sunset.png' },
      { name: 'Red', link: 'Background/Red.png' },
    ],
  },
  {
    name: 'Body',
    items: [
      { name: 'Honey', link: 'Body/Honey.png' },
      { name: 'Umber', link: 'Body/Umber.png' },
      { name: 'Espresso', link: 'Body/Espresso.png' },
      { name: 'Light', link: 'Body/Light.png' },
      { name: 'Pale', link: 'Body/Pale.png' },
      { name: 'Porcelean', link: 'Body/Porcelean.png' },
    ],
  },
  {
    name: 'Eyes',
    items: [
      { name: 'Yellow', link: 'Eyes/Yellow.png' },
      { name: 'Blue', link: 'Eyes/Blue.png' },
      { name: 'Black', link: 'Eyes/Black.png' },
      { name: 'Violet', link: 'Eyes/Violet.png' },
      { name: 'Green', link: 'Eyes/Green.png' },
      { name: 'Brown', link: 'Eyes/Brown.png' },
      { name: 'Red', link: 'Eyes/Red.png' },
    ],
  },
  {
    name: 'Hair',
    items: [
      { name: 'Shaggy-Dark-Blonde', link: 'Hair/Shaggy-Dark-Blonde.png' },
      { name: 'Bangs-Purple', link: 'Hair/Bangs-Purple.png' },
      { name: 'Bangs-Grey', link: 'Hair/Bangs-Grey.png' },
      { name: 'Shaggy Mullet Green', link: 'Hair/Shaggy Mullet Green.png' },
      { name: 'Windswept Brown', link: 'Hair/Windswept Brown.png' },
      { name: 'Curtains Dark Blonde', link: 'Hair/Curtains Dark Blonde.png' },
      { name: 'Curtains Green', link: 'Hair/Curtains Green.png' },
      { name: 'Freeform Loc Flop Dark Blonde', link: 'Hair/Freeform Loc Flop Dark Blonde.png' },
      { name: 'Bangs-Black', link: 'Hair/Bangs-Black.png' },
      { name: 'Freeform Loc Flop Brown', link: 'Hair/Freeform Loc Flop Brown.png' },
      { name: 'Tied Locs Black', link: 'Hair/Tied Locs Black.png' },
      { name: 'Shaggy-Brown', link: 'Hair/Shaggy-Brown.png' },
      { name: 'Tied Locs Grey', link: 'Hair/Tied Locs Grey.png' },
      { name: 'Shaggy-Blonde', link: 'Hair/Shaggy-Blonde.png' },
      { name: 'Freeform Loc Flop Red', link: 'Hair/Freeform Loc Flop Red.png' },
      { name: 'Windswept Blonde', link: 'Hair/Windswept Blonde.png' },
      { name: 'Tied Locs Dark Blonde', link: 'Hair/Tied Locs Dark Blonde.png' },
      { name: 'Curtains Grey', link: 'Hair/Curtains Grey.png' },
      { name: 'Shaggy-Blue', link: 'Hair/Shaggy-Blue.png' },
      { name: 'Windswept Blue', link: 'Hair/Windswept Blue.png' },
      { name: 'Shaggy Mullet Brown', link: 'Hair/Shaggy Mullet Brown.png' },
      { name: 'Windswept Green', link: 'Hair/Windswept Green.png' },
      { name: 'Curtains Brown', link: 'Hair/Curtains Brown.png' },
      { name: 'Shaggy Mullet Blue', link: 'Hair/Shaggy Mullet Blue.png' },
      { name: 'Freeform Loc Flop Green', link: 'Hair/Freeform Loc Flop Green.png' },
      { name: 'Shaggy Mullet Red', link: 'Hair/Shaggy Mullet Red.png' },
      { name: 'Shaggy Mullet Purple', link: 'Hair/Shaggy Mullet Purple.png' },
      { name: 'Freedom-Loc-Flop-Grey', link: 'Hair/Freedom-Loc-Flop-Grey.png' },
      { name: 'Curtains Blonde', link: 'Hair/Curtains Blonde.png' },
      { name: 'Shaggy-Green', link: 'Hair/Shaggy-Green.png' },
      { name: 'Tied Locs Purple', link: 'Hair/Tied Locs Purple.png' },
      { name: 'Freeform Loc Flop Purple', link: 'Hair/Freeform Loc Flop Purple.png' },
      { name: 'Shaggy-Black', link: 'Hair/Shaggy-Black.png' },
      { name: 'Shaggy Mullet Grey', link: 'Hair/Shaggy Mullet Grey.png' },
      { name: 'Shaggy-Purple', link: 'Hair/Shaggy-Purple.png' },
      { name: 'Tied Locs Brown', link: 'Hair/Tied Locs Brown.png' },
      { name: 'Windswept Red', link: 'Hair/Windswept Red.png' },
      { name: 'Freeform Loc Flop Blue', link: 'Hair/Freeform Loc Flop Blue.png' },
      { name: 'Windswept Black', link: 'Hair/Windswept Black.png' },
      { name: 'Bangs-Brown', link: 'Hair/Bangs-Brown.png' },
      { name: 'Freeform Loc Flop Black', link: 'Hair/Freeform Loc Flop Black.png' },
      { name: 'Curtains Red', link: 'Hair/Curtains Red.png' },
      { name: 'Bangs-Dark-Blonde', link: 'Hair/Bangs-Dark-Blonde.png' },
      { name: 'Bangs-Blonde', link: 'Hair/Bangs-Blonde.png' },
      { name: 'Shaggy Mullet Dark Blonde', link: 'Hair/Shaggy Mullet Dark Blonde.png' },
      { name: 'Curtains Blue', link: 'Hair/Curtains Blue.png' },
      { name: 'Windswept Grey', link: 'Hair/Windswept Grey.png' },
      { name: 'Shaggy-Grey', link: 'Hair/Shaggy-Grey.png' },
      { name: 'Tied Locs Green', link: 'Hair/Tied Locs Green.png' },
      { name: 'Freeform Loc Flop Blonde', link: 'Hair/Freeform Loc Flop Blonde.png' },
      { name: 'Tied Locs Blonde', link: 'Hair/Tied Locs Blonde.png' },
      { name: 'Curtains Purple', link: 'Hair/Curtains Purple.png' },
      { name: 'Shaggy Mullet Blonde', link: 'Hair/Shaggy Mullet Blonde.png' },
      { name: 'Shaggy-Red', link: 'Hair/Shaggy-Red.png' },
      { name: 'Curtains Black', link: 'Hair/Curtains Black.png' },
      { name: 'Bangs-Green', link: 'Hair/Bangs-Green.png' },
      { name: 'Bangs-Red', link: 'Hair/Bangs-Red.png' },
      { name: 'Tied Locs Blue', link: 'Hair/Tied Locs Blue.png' },
      { name: 'Tied Locs Red', link: 'Hair/Tied Locs Red.png' },
      { name: 'Windswept Dark Blonde', link: 'Hair/Windswept Dark Blonde.png' },
      { name: 'Shaggy Mullet Black', link: 'Hair/Shaggy Mullet Black.png' },
      { name: 'Windswept Purple', link: 'Hair/Windswept Purple.png' },
      { name: 'Bangs-Blue', link: 'Hair/Bangs-Blue.png' },
    ],
  },
  {
    name: 'Clothing',
    items: [
      { name: 'Monk Orange Red', link: 'Clothing/Monk Orange Red.png' },
      { name: 'Merchant Green', link: 'Clothing/Merchant Green.png' },
      { name: 'Merchant Blue Red', link: 'Clothing/Merchant Blue Red.png' },
      { name: 'Highborne Purple', link: 'Clothing/Highborne Purple.png' },
      { name: 'Fisherman Purple', link: 'Clothing/Fisherman Purple.png' },
      { name: 'Fisherman Green', link: 'Clothing/Fisherman Green.png' },
      { name: 'Merchant Blue Grey', link: 'Clothing/Merchant Blue Grey.png' },
      { name: 'Fisherman Natural', link: 'Clothing/Fisherman Natural.png' },
      { name: 'Highborne Gold', link: 'Clothing/Highborne Gold.png' },
      { name: 'Farmer Red', link: 'Clothing/Farmer Red.png' },
      { name: 'Monk White Blue', link: 'Clothing/Monk White Blue.png' },
      { name: 'Monk Brown Green', link: 'Clothing/Monk Brown Green.png' },
      { name: 'Highborne Blue', link: 'Clothing/Highborne Blue.png' },
      { name: 'Farmer Green', link: 'Clothing/Farmer Green.png' },
      { name: 'Farmer Blue', link: 'Clothing/Farmer Blue.png' },
    ],
  },
];

export const getRandomNFT = () => {
  const selectedTraits = [];
  for (const trait of traits) {
    selectedTraits.push(trait.items[Math.floor(Math.random() * trait.items.length)]);
  }

  return selectedTraits;
};
